// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gvwtsrxttnqsnpanjppk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_2MeZpKvD8wUu1dJ6wX8_yQ_DK_Zfjfd";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);