// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bqbyrdwuailtmavbosyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "VOTRE_CLE_PUBLIQUE_ANON_KEY_ICI"; // Placeholder - Veuillez me fournir votre clé publique

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);