// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bqbyrdwuailtmavbosyr.supabase.co";
// REMPLACEZ LA VALEUR CI-DESSOUS PAR VOTRE CLÉ ANON (PUBLIC KEY)
const SUPABASE_PUBLISHABLE_KEY = "VOTRE_CLE_ANON_ICI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);